# Generated by Django 2.2.10 on 2021-10-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulk',
            name='bulk_end_time_slot',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
