# Generated by Django 2.2.10 on 2021-10-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211006_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulk',
            name='passed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bulk',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
