# Generated by Django 2.2.10 on 2021-10-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_request_result_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('IN_QUEUE', 'In Queue'), ('PENDING', 'Pending')], max_length=50),
        ),
    ]
