# Generated by Django 2.2.10 on 2021-10-07 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211007_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='bulk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='home.Bulk'),
        ),
    ]
