# Generated by Django 2.2.10 on 2021-10-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211007_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='result',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
