# Generated by Django 2.2.10 on 2021-10-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211009_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='popular_tag',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
