# Generated by Django 2.2.10 on 2021-10-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_plan_popular_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='order',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
