# Generated by Django 2.2.10 on 2021-10-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211010_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='popular_tag',
        ),
        migrations.AddField(
            model_name='plan',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
