# Generated by Django 2.2.10 on 2021-10-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211010_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='modify_time_slot',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
