# Generated by Django 2.2.10 on 2021-10-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_plan_modify_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
