# Generated by Django 2.2.10 on 2021-10-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20211012_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paying_id',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
