# Generated by Django 2.2.10 on 2021-10-26 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211016_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Other_Fields',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
