# Generated by Django 2.2.10 on 2021-10-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_user_other_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_other_fields',
            name='remain_count',
            field=models.IntegerField(default=10),
        ),
    ]
