# Generated by Django 2.2.10 on 2021-10-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_user_other_fields_remain_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_other_fields',
            name='user_key',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
