# Generated by Django 2.2.10 on 2021-10-26 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0017_user_other_fields_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_other_fields',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='other_fields', to=settings.AUTH_USER_MODEL),
        ),
    ]
