# Generated by Django 2.2.10 on 2021-10-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_user_other_fields_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_other_fields',
            name='remain_count',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
