# Generated by Django 2.2.10 on 2021-11-06 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20211026_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_other_fields',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='other_fields', to='home.Plan'),
        ),
    ]
