# Generated by Django 2.2.10 on 2021-11-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_user_other_fields_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulk',
            name='request_type',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('MYSPACE', 'Myspace'), ('PLAXO', 'Plaxo'), ('INSTAGRAM', 'Instagram'), ('TUMBLR', 'Tumblr'), ('LIVEJOURNAL', 'Livejournal'), ('FLICKR', 'Flickr'), ('YOUTUBE', 'Youtube'), ('PINTEREST', 'Pinterest'), ('VIMEO', 'Vimeo'), ('SPOTIFY', 'Spotify'), ('TWITCH', 'Twitch'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('WECHAT', 'WeChat'), ('TIKTOK', 'TikTok'), ('QQ', 'QQ'), ('SNAPCHAT', 'Snapchat'), ('REDDIT', 'Reddit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('MYSPACE', 'Myspace'), ('PLAXO', 'Plaxo'), ('INSTAGRAM', 'Instagram'), ('TUMBLR', 'Tumblr'), ('LIVEJOURNAL', 'Livejournal'), ('FLICKR', 'Flickr'), ('YOUTUBE', 'Youtube'), ('PINTEREST', 'Pinterest'), ('VIMEO', 'Vimeo'), ('SPOTIFY', 'Spotify'), ('TWITCH', 'Twitch'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('WECHAT', 'WeChat'), ('TIKTOK', 'TikTok'), ('QQ', 'QQ'), ('SNAPCHAT', 'Snapchat'), ('REDDIT', 'Reddit')], max_length=50),
        ),
    ]
