# Generated by Django 2.2.10 on 2021-11-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20211108_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
