# Generated by Django 2.2.10 on 2021-12-09 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0022_request_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_time_slot',
            new_name='question_time_slot',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='body',
        ),
        migrations.AddField(
            model_name='ticket',
            name='admin_seen_status',
            field=models.CharField(choices=[('SEEN', 'Seen'), ('UNSEEN', 'Unseen')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='client_seen_status',
            field=models.CharField(choices=[('SEEN', 'Seen'), ('UNSEEN', 'Unseen')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='message_count',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='bulk',
            name='request_type',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('WIKIPEDIA', 'Wikipedia'), ('REDDIT', 'Reddit'), ('IMDB', 'IMDb'), ('BOOKING', 'Booking'), ('GITHUB', 'Github'), ('GOOGLESCHOLAR', 'GoogleScholar'), ('PINTEREST', 'Pinterest'), ('VIMEO', 'Vimeo'), ('SPOTIFY', 'Spotify'), ('TWITCH', 'Twitch'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('WECHAT', 'WeChat'), ('TIKTOK', 'TikTok'), ('SNAPCHAT', 'Snapchat'), ('FLICKR', 'Flickr'), ('MYSPACE', 'Myspace'), ('PLAXO', 'Plaxo'), ('TUMBLR', 'Tumblr'), ('LIVEJOURNAL', 'Livejournal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('WIKIPEDIA', 'Wikipedia'), ('REDDIT', 'Reddit'), ('IMDB', 'IMDb'), ('BOOKING', 'Booking'), ('GITHUB', 'Github'), ('GOOGLESCHOLAR', 'GoogleScholar'), ('PINTEREST', 'Pinterest'), ('VIMEO', 'Vimeo'), ('SPOTIFY', 'Spotify'), ('TWITCH', 'Twitch'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('WECHAT', 'WeChat'), ('TIKTOK', 'TikTok'), ('SNAPCHAT', 'Snapchat'), ('FLICKR', 'Flickr'), ('MYSPACE', 'Myspace'), ('PLAXO', 'Plaxo'), ('TUMBLR', 'Tumblr'), ('LIVEJOURNAL', 'Livejournal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('USER_ANSWERED', 'User Answered'), ('ADMIN_ANSWERED', 'Admin Answered'), ('USER_CREATED', 'User Created'), ('ADMIN_NOTIFICATION', 'Admin Notification')], max_length=50),
        ),
        migrations.CreateModel(
            name='Ticket_Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.CharField(blank=True, max_length=10000)),
                ('seen_status', models.CharField(choices=[('SEEN', 'Seen'), ('UNSEEN', 'Unseen')], max_length=50)),
                ('time_slot', models.DateTimeField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='home.Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
