# Generated by Django 2.2.10 on 2021-12-10 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20211209_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='empty_status',
            field=models.CharField(choices=[('EMPTY', 'Empty'), ('NOT_EMPTY', 'Not Empty')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
