# Generated by Django 2.2.10 on 2021-12-10 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_ticket_empty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_message',
            name='user_type',
            field=models.CharField(choices=[('USER', 'User'), ('ADMINISTRATOR', 'Administrator')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='message_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
