# Generated by Django 2.2.10 on 2021-12-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20211210_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_message',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('ADMINISTRATOR', 'Administrator')], max_length=50),
        ),
    ]
