# Generated by Django 2.2.10 on 2022-01-04 09:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20211222_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remain_count', models.IntegerField(blank=True, default=10)),
                ('title', models.CharField(max_length=1500)),
                ('image_name', models.CharField(max_length=1500)),
                ('time_slot', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='bulk',
            name='request_type',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'c'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('WIKIPEDIA', 'Wikipedia'), ('REDDIT', 'Reddit'), ('IMDB', 'IMDb'), ('BOOKING', 'Booking'), ('GITHUB', 'Github'), ('GOOGLESCHOLAR', 'GoogleScholar'), ('PINTEREST', 'Pinterest'), ('VIMEO', 'Vimeo'), ('SPOTIFY', 'Spotify'), ('TWITCH', 'Twitch'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('WECHAT', 'WeChat'), ('TIKTOK', 'TikTok'), ('SNAPCHAT', 'Snapchat'), ('FLICKR', 'Flickr'), ('MYSPACE', 'Myspace'), ('PLAXO', 'Plaxo'), ('TUMBLR', 'Tumblr'), ('LIVEJOURNAL', 'Livejournal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'c'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('WIKIPEDIA', 'Wikipedia'), ('REDDIT', 'Reddit'), ('IMDB', 'IMDb'), ('BOOKING', 'Booking'), ('GITHUB', 'Github'), ('GOOGLESCHOLAR', 'GoogleScholar'), ('PINTEREST', 'Pinterest'), ('VIMEO', 'Vimeo'), ('SPOTIFY', 'Spotify'), ('TWITCH', 'Twitch'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('WECHAT', 'WeChat'), ('TIKTOK', 'TikTok'), ('SNAPCHAT', 'Snapchat'), ('FLICKR', 'Flickr'), ('MYSPACE', 'Myspace'), ('PLAXO', 'Plaxo'), ('TUMBLR', 'Tumblr'), ('LIVEJOURNAL', 'Livejournal')], max_length=50),
        ),
        migrations.CreateModel(
            name='Post_Paragraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.CharField(blank=True, max_length=10000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='home.Post')),
            ],
        ),
    ]
