# Generated by Django 2.2.10 on 2022-01-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20220104_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='remain_count',
        ),
    ]
