# Generated by Django 2.2.10 on 2022-01-05 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_post_remain_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_paragraph',
            name='time_slot',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
