# Generated by Django 2.2.10 on 2022-01-05 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_post_paragraph_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
