# Generated by Django 2.2.10 on 2022-01-10 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='process_status',
            field=models.CharField(choices=[('NONE', 'None'), ('FALSE', 'False'), ('PROCESS', 'Process'), ('TRUE', 'True')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
