# Generated by Django 2.2.10 on 2022-01-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_request_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='process_status',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('FALSE', 'False'), ('PROCESS', 'Process'), ('TRUE', 'True')], max_length=50, null=True),
        ),
    ]
