# Generated by Django 2.2.10 on 2022-01-11 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20220110_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='process_status',
        ),
        migrations.AlterField(
            model_name='bulk',
            name='request_type',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('WIKIPEDIA', 'Wikipedia'), ('REDDIT', 'Reddit'), ('IMDB', 'IMDb'), ('BOOKING', 'Booking'), ('GITHUB', 'Github'), ('GOOGLESCHOLAR', 'GoogleScholar'), ('PINTEREST', 'Pinterest'), ('VIMEO', 'Vimeo'), ('SPOTIFY', 'Spotify'), ('TWITCH', 'Twitch'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('WECHAT', 'WeChat'), ('TIKTOK', 'TikTok'), ('SNAPCHAT', 'Snapchat'), ('FLICKR', 'Flickr'), ('MYSPACE', 'Myspace'), ('PLAXO', 'Plaxo'), ('TUMBLR', 'Tumblr'), ('LIVEJOURNAL', 'Livejournal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('WIKIPEDIA', 'Wikipedia'), ('REDDIT', 'Reddit'), ('IMDB', 'IMDb'), ('BOOKING', 'Booking'), ('GITHUB', 'Github'), ('GOOGLESCHOLAR', 'GoogleScholar'), ('PINTEREST', 'Pinterest'), ('VIMEO', 'Vimeo'), ('SPOTIFY', 'Spotify'), ('TWITCH', 'Twitch'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('WECHAT', 'WeChat'), ('TIKTOK', 'TikTok'), ('SNAPCHAT', 'Snapchat'), ('FLICKR', 'Flickr'), ('MYSPACE', 'Myspace'), ('PLAXO', 'Plaxo'), ('TUMBLR', 'Tumblr'), ('LIVEJOURNAL', 'Livejournal')], max_length=50),
        ),
        migrations.CreateModel(
            name='Request_Bulk_Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_status', models.CharField(blank=True, choices=[('NONE', 'None'), ('FALSE', 'False'), ('PROCESS', 'Process'), ('TRUE', 'True')], max_length=50, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='home.Request')),
            ],
        ),
    ]
