# Generated by Django 2.2.10 on 2022-01-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20220111_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulk',
            name='status',
            field=models.CharField(choices=[('IN_QUEUE', 'In Queue'), ('FAILED', 'Failed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=50),
        ),
    ]
