# Generated by Django 2.2.10 on 2022-01-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20220111_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_bulk_process',
            name='query',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
