# Generated by Django 2.2.10 on 2022-01-12 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_request_bulk_process_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_bulk_process',
            name='request_type',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('WIKIPEDIA', 'Wikipedia'), ('REDDIT', 'Reddit'), ('IMDB', 'IMDb'), ('BOOKING', 'Booking'), ('GITHUB', 'Github'), ('GOOGLESCHOLAR', 'GoogleScholar'), ('PINTEREST', 'Pinterest'), ('VIMEO', 'Vimeo'), ('SPOTIFY', 'Spotify'), ('TWITCH', 'Twitch'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('WECHAT', 'WeChat'), ('TIKTOK', 'TikTok'), ('SNAPCHAT', 'Snapchat'), ('FLICKR', 'Flickr'), ('MYSPACE', 'Myspace'), ('PLAXO', 'Plaxo'), ('TUMBLR', 'Tumblr'), ('LIVEJOURNAL', 'Livejournal')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
