# Generated by Django 2.2.10 on 2022-05-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_request_bulk_process_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulk',
            name='request_type',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('WIKIPEDIA', 'Wikipedia'), ('REDDIT', 'Reddit'), ('IMDB', 'IMDb'), ('BOOKING', 'Booking'), ('GITHUB', 'Github'), ('GOOGLESCHOLAR', 'GoogleScholar'), ('CRUNCHBASE', 'Crunchbase'), ('ZOOMINFO', 'Zoominfo'), ('STACKOVERFLOW', 'StackOverflow'), ('AMAZON', 'Amazon'), ('PINTEREST', 'Pinterest'), ('VIMEO', 'Vimeo'), ('SPOTIFY', 'Spotify'), ('TWITCH', 'Twitch'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('WECHAT', 'WeChat'), ('TIKTOK', 'TikTok'), ('SNAPCHAT', 'Snapchat'), ('FLICKR', 'Flickr'), ('MYSPACE', 'Myspace'), ('PLAXO', 'Plaxo'), ('TUMBLR', 'Tumblr'), ('LIVEJOURNAL', 'Livejournal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('WIKIPEDIA', 'Wikipedia'), ('REDDIT', 'Reddit'), ('IMDB', 'IMDb'), ('BOOKING', 'Booking'), ('GITHUB', 'Github'), ('GOOGLESCHOLAR', 'GoogleScholar'), ('CRUNCHBASE', 'Crunchbase'), ('ZOOMINFO', 'Zoominfo'), ('STACKOVERFLOW', 'StackOverflow'), ('AMAZON', 'Amazon'), ('PINTEREST', 'Pinterest'), ('VIMEO', 'Vimeo'), ('SPOTIFY', 'Spotify'), ('TWITCH', 'Twitch'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('WECHAT', 'WeChat'), ('TIKTOK', 'TikTok'), ('SNAPCHAT', 'Snapchat'), ('FLICKR', 'Flickr'), ('MYSPACE', 'Myspace'), ('PLAXO', 'Plaxo'), ('TUMBLR', 'Tumblr'), ('LIVEJOURNAL', 'Livejournal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request_bulk_process',
            name='request_type',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('WIKIPEDIA', 'Wikipedia'), ('REDDIT', 'Reddit'), ('IMDB', 'IMDb'), ('BOOKING', 'Booking'), ('GITHUB', 'Github'), ('GOOGLESCHOLAR', 'GoogleScholar'), ('CRUNCHBASE', 'Crunchbase'), ('ZOOMINFO', 'Zoominfo'), ('STACKOVERFLOW', 'StackOverflow'), ('AMAZON', 'Amazon'), ('PINTEREST', 'Pinterest'), ('VIMEO', 'Vimeo'), ('SPOTIFY', 'Spotify'), ('TWITCH', 'Twitch'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('WECHAT', 'WeChat'), ('TIKTOK', 'TikTok'), ('SNAPCHAT', 'Snapchat'), ('FLICKR', 'Flickr'), ('MYSPACE', 'Myspace'), ('PLAXO', 'Plaxo'), ('TUMBLR', 'Tumblr'), ('LIVEJOURNAL', 'Livejournal')], max_length=50),
        ),
    ]
