# Generated by Django 2.2.10 on 2022-08-21 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20220528_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount_Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_slot', models.DateTimeField(blank=True, default=None, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('value', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('ENABLE', 'Enable'), ('DISABLE', 'Disable')], max_length=50)),
            ],
        ),
    ]
