# Generated by Django 2.2.10 on 2023-02-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulk',
            name='request_type',
            field=models.CharField(choices=[('SENTIMENT_ANALYSIS', 'Sentiment Analysis'), ('KEYWORD_EXTRACTION', 'Keyword Extraction'), ('NAMED_ENTITY_RECOGNITION', 'Named-Entity Recognition')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('SENTIMENT_ANALYSIS', 'Sentiment Analysis'), ('KEYWORD_EXTRACTION', 'Keyword Extraction'), ('NAMED_ENTITY_RECOGNITION', 'Named-Entity Recognition')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request_bulk_process',
            name='request_type',
            field=models.CharField(choices=[('SENTIMENT_ANALYSIS', 'Sentiment Analysis'), ('KEYWORD_EXTRACTION', 'Keyword Extraction'), ('NAMED_ENTITY_RECOGNITION', 'Named-Entity Recognition')], max_length=50),
        ),
    ]
