# Generated by Django 2.2.10 on 2023-02-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20230209_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulk',
            name='request_type',
            field=models.CharField(choices=[('SENTIMENT_ANALYSIS', 'Sentiment Analysis')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('SENTIMENT_ANALYSIS', 'Sentiment Analysis')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request_bulk_process',
            name='request_type',
            field=models.CharField(choices=[('SENTIMENT_ANALYSIS', 'Sentiment Analysis')], max_length=50),
        ),
    ]
