# Generated by Django 2.2.10 on 2023-03-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20230228_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulk',
            name='request_type',
            field=models.CharField(choices=[('SENTIMENT_ANALYSIS', 'Sentiment Analysis'), ('KEYWORD_EXTRACTION', 'Keyword Extraction'), ('NAMED_ENTITY_RECOGNITION', 'Named-Entity Recognition'), ('YOUTUBE_CATEGORY_EXTRACTION', 'Youtube-Category Extraction')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('SENTIMENT_ANALYSIS', 'Sentiment Analysis'), ('KEYWORD_EXTRACTION', 'Keyword Extraction'), ('NAMED_ENTITY_RECOGNITION', 'Named-Entity Recognition'), ('YOUTUBE_CATEGORY_EXTRACTION', 'Youtube-Category Extraction')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request_bulk_process',
            name='request_type',
            field=models.CharField(choices=[('SENTIMENT_ANALYSIS', 'Sentiment Analysis'), ('KEYWORD_EXTRACTION', 'Keyword Extraction'), ('NAMED_ENTITY_RECOGNITION', 'Named-Entity Recognition'), ('YOUTUBE_CATEGORY_EXTRACTION', 'Youtube-Category Extraction')], max_length=50),
        ),
    ]
