# Generated by Django 2.2.10 on 2023-04-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20230321_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_other_fields',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
