# Generated by Django 2.2.10 on 2023-04-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_user_other_fields_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_other_fields',
            name='promotion_code_used',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
