# Generated by Django 2.2.10 on 2023-07-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_user_other_fields_promotion_code_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_other_fields',
            name='remain_count',
            field=models.IntegerField(blank=True, default=50),
        ),
    ]
